Add Author Link MetaData
lelionvert/a-software-crafter-s-journey pull request #12
Opened 2020-03-06 18:26 UTC by MaximeRnR

2021-05-24 16:21 UTC, bachrc commented
Quid du coup si l'on ne renseigne pas de lien pour cet auteur ? Il me semble qu'il y a un lien vide quand même, mais s'il n'y a pas de lien spécifié, on est pas censés avoir de lien je pense ?

2021-05-24 16:22 UTC, bachrc requested changes

2021-05-24 16:22 UTC, bachrc commented on pages/article.vue
> +                        {{ publishedByLabel }} <a :href="article.author_link" target="_blank">{{ article.author }}</a>
Ici, on mets un lien quoiqu'il arrive, or le tag devrait-être facultatif

2021-05-26 12:17 UTC, MaximeRnR commented on pages/article.vue
> +                        {{ publishedByLabel }} <a :href="article.author_link" target="_blank">{{ article.author }}</a>
Hésite pas à faire la modification dans la PR mdr je me souviens plus ça a 1 ans mdr

2022-07-05 09:09 UTC, closed without merging